### PR TITLE
Support test_retry in rdbms storage

### PR DESCRIPTION
**Pull request by rihter007**

### CODE REVIEW

**Comment by mimir-d** [comment]
is this based on one of the other PRs? not sure if it'll break if merged right now

**Comment by rihter007** [comment]
> is this based on one of the other PRs? not sure if it'll break if merged right now

Yes it is based on PR37, so PR 37 should be landed first

**Comment by mimir-d** [comment]
ok, i'll give it an accept now, before merging #37, just make sure it doesnt break

**Review by mimir-d — APPROVED** [review]

**Comment by rihter007** [comment]
Sorry @mimir-d , could you please re-accept the PR?

**Review by mimir-d — APPROVED** [review]

**Pull request merged**
